controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

settings:
    path: /settings
    controller: App\Controller\SettingsController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]